#index:
#    path: /
#    controller: App\Controller\DefaultController::index
container_add:
    path: /container
    methods: post
    controller: App\Controller\ContainerController::actionAddContainer

container_slice:
    path: /container/slice
    methods: get
    controller: App\Controller\ContainerController::actionGetContainerSlice

container_get_by_id:
    path: /container/
    methods: get
    controller: App\Controller\ContainerController::actionGetContainerById

